# Generated by Django 5.1.6 on 2025-05-02 06:17

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postattachment',
            name='video',
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.FileField(upload_to='posts/attachments', validators=[posts.models.validate_svg_or_image]),
        ),
    ]
