# Generated by Django 5.1.6 on 2025-04-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.CharField(choices=[('only_me', 'only_me'), ('public', 'public')], default='public', max_length=10),
        ),
    ]
