# Generated by Django 5.1.6 on 2025-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_postattachment_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feeling',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
