# Generated by Django 5.1.6 on 2025-05-03 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='posts.post'),
        ),
    ]
