# Generated by Django 4.2.16 on 2025-05-29 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_friends_user_friends_count_friendshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
