# Generated by Django 5.1.6 on 2025-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_date_of_birth_userprofile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('local', 'local'), ('google', 'google'), ('facebook', 'facebook'), ('linkedin', 'linkedin'), ('twitter', 'twitter')], default='local', max_length=50),
        ),
    ]
