# Generated by Django 4.2.16 on 2025-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('comment_like', 'Comment Like'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_rejected', 'Friend Request Rejected'), ('friend_request_cancelled', 'Friend Request Cancelled')], max_length=50),
        ),
    ]
